-- ==================================================
-- Set AUTOCOMMIT OFF
-- ==================================================
--SET AUTOCOMMIT OFF;

-- ==================================================
-- Trigger: CREATE Triggers
-- --------------------------------------------------
-- You have the option to specify whether a trigger is a statement trigger or a row trigger.
-- If it is not specified in the CREATE TRIGGER statement via FOR EACH clause, then the
-- trigger is a statement trigger by default.
-- --------------------------------------------------
-- Statement Triggers
-- A statement trigger fires once per triggering event and regardless of whether any rows
-- are modified by the insert, update, or delete event.
-- --------------------------------------------------
-- Row Triggers
-- A row trigger fires once for each row affected by the triggering event.
-- If no rows are affected, the trigger does not fire.
-- ==================================================
-- CREATE TRIGGER triggerName
-- { AFTER | NO CASCADE BEFORE }
-- { INSERT | DELETE | UPDATE [ OF columnName [ , columnName ]* ] }
-- ON tableName
-- [ referencingClause ]
-- [ FOR EACH { ROW | STATEMENT } ] [ MODE DB2SQL ]
-- [ WHEN ( booleanExpression ) ]
-- triggeredSQLStatement
-- Before or after: WHEN
-- ==================================================
CREATE TRIGGER ARTEFACT_AFTER_INSERT_TRIGGER
	AFTER INSERT ON ARTEFACT
	REFERENCING NEW AS AIR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'ARTEFACT', 'Insert Row'
	,'ID=' || CAST (AIR.ARTEFACT_ID AS CHAR(10))
	,'VERSION=' || CAST (AIR.ARTEFACT_VERSION AS CHAR(10))
	,'ACTOR_ID=' || CAST (AIR.ARTEFACT_ACTOR_ID AS CHAR(10))
	,'STATUS_ID=' || CAST (AIR.ARTEFACT_STATUS_ID AS CHAR(10))
	,'TIMBER_ID=' || CAST (AIR.ARTEFACT_TIMBER_ID AS CHAR(10))
	,'ORDINAL=' || CAST(AIR.ARTEFACT_ORDINAL AS CHAR(10))
	,'PRICE=' || CAST (AIR.ARTEFACT_PRICE AS CHAR(10))
	,'IMAGENAME=' || AIR.ARTEFACT_IMAGENAME
	,'ORIGIN=' || AIR.ARTEFACT_ORIGIN
	,'COMMENT=' || AIR.ARTEFACT_COMMENT
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER ARTEFACT_BEFORE_UPDATE_TRIGGER
	AFTER UPDATE ON ARTEFACT
	REFERENCING OLD AS AUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'ARTEFACT', 'Before Update Row'
	,'ID=' || CAST (AUR.ARTEFACT_ID AS CHAR(10))
	,'VERSION=' || CAST (AUR.ARTEFACT_VERSION AS CHAR(10))
	,'ACTOR_ID=' || CAST (AUR.ARTEFACT_ACTOR_ID AS CHAR(10))
	,'STATUS_ID=' || CAST (AUR.ARTEFACT_STATUS_ID AS CHAR(10))
	,'TIMBER_ID=' || CAST (AUR.ARTEFACT_TIMBER_ID AS CHAR(10))
	,'ORDINAL=' || CAST(AUR.ARTEFACT_ORDINAL AS CHAR(10))
	,'PRICE=' || CAST (AUR.ARTEFACT_PRICE AS CHAR(10))
	,'IMAGENAME=' || AUR.ARTEFACT_IMAGENAME
	,'ORIGIN=' || AUR.ARTEFACT_ORIGIN
	,'COMMENT=' || AUR.ARTEFACT_COMMENT
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER ARTEFACT_AFTER_UPDATE_TRIGGER
	AFTER UPDATE ON ARTEFACT
	REFERENCING NEW AS AUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'ARTEFACT', 'After Update Row'
	,'ID=' || CAST (AUR.ARTEFACT_ID AS CHAR(10))
	,'VERSION=' || CAST (AUR.ARTEFACT_VERSION AS CHAR(10))
	,'ACTOR_ID=' || CAST (AUR.ARTEFACT_ACTOR_ID AS CHAR(10))
	,'STATUS_ID=' || CAST (AUR.ARTEFACT_STATUS_ID AS CHAR(10))
	,'TIMBER_ID=' || CAST (AUR.ARTEFACT_TIMBER_ID AS CHAR(10))
	,'ORDINAL=' || CAST(AUR.ARTEFACT_ORDINAL AS CHAR(10))
	,'PRICE=' || CAST (AUR.ARTEFACT_PRICE AS CHAR(10))
	,'IMAGENAME=' || AUR.ARTEFACT_IMAGENAME
	,'ORIGIN=' || AUR.ARTEFACT_ORIGIN
	,'COMMENT=' || AUR.ARTEFACT_COMMENT
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER ARTEFACT_AFTER_DELETE_TRIGGER
	AFTER DELETE ON ARTEFACT
	REFERENCING OLD AS ADR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (CURRENT_TIMESTAMP, CURRENT_USER, 'ARTEFACT', 'Delete Row'
	,'ID=' || CAST (ADR.ARTEFACT_ID AS CHAR(10))
	,'VERSION=' || CAST (ADR.ARTEFACT_VERSION AS CHAR(10))
	,'ACTOR_ID=' || CAST (ADR.ARTEFACT_ACTOR_ID AS CHAR(10))
	,'STATUS_ID=' || CAST (ADR.ARTEFACT_STATUS_ID AS CHAR(10))
	,'TIMBER_ID=' || CAST (ADR.ARTEFACT_TIMBER_ID AS CHAR(10))
	,'ORDINAL=' || CAST(ADR.ARTEFACT_ORDINAL AS CHAR(10))
	,'PRICE=' || CAST (ADR.ARTEFACT_PRICE AS CHAR(10))
	,'IMAGENAME=' || ADR.ARTEFACT_IMAGENAME
	,'ORIGIN=' || ADR.ARTEFACT_ORIGIN
	,'COMMENT=' || ADR.ARTEFACT_COMMENT
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER BOTANICSYSTEM_AFTER_INSERT_TRIGGER
	AFTER INSERT ON BOTANICSYSTEM
	REFERENCING NEW AS BSIR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'BOTANICSYSTEM', 'Insert Row'
	,'ID=' || CAST (BSIR.BOTANICSYSTEM_ID AS CHAR(10))
	,'VERSION=' || CAST (BSIR.BOTANICSYSTEM_VERSION AS CHAR(10))
	,'ORDINAL=' || CAST (BSIR.BOTANICSYSTEM_ORDINAL AS CHAR(10))
	,'ORDNUNG=' || BSIR.BOTANICSYSTEM_ORDNUNG
	,'FAMILIE=' || BSIR.BOTANICSYSTEM_FAMILIE
	,'UNTERFAMILIE=' || BSIR.BOTANICSYSTEM_UNTERFAMILIE
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER BOTANICSYSTEM_BEFORE_UPDATE_TRIGGER
	AFTER UPDATE ON BOTANICSYSTEM
	REFERENCING OLD AS BSUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'BOTANICSYSTEM', 'Before Update Row'
	,'ID=' || CAST (BSUR.BOTANICSYSTEM_ID AS CHAR(10))
	,'VERSION=' || CAST (BSUR.BOTANICSYSTEM_VERSION AS CHAR(10))
	,'ORDINAL=' || CAST (BSUR.BOTANICSYSTEM_ORDINAL AS CHAR(10))
	,'ORDNUNG=' || BSUR.BOTANICSYSTEM_ORDNUNG
	,'FAMILIE=' || BSUR.BOTANICSYSTEM_FAMILIE
	,'UNTERFAMILIE=' || BSUR.BOTANICSYSTEM_UNTERFAMILIE
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER BOTANICSYSTEM_AFTER_UPDATE_TRIGGER
	AFTER UPDATE ON BOTANICSYSTEM
	REFERENCING NEW AS BSUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'BOTANICSYSTEM', 'After Update Row'
	,'ID=' || CAST (BSUR.BOTANICSYSTEM_ID AS CHAR(10))
	,'VERSION=' || CAST (BSUR.BOTANICSYSTEM_VERSION AS CHAR(10))
	,'ORDINAL=' || CAST (BSUR.BOTANICSYSTEM_ORDINAL AS CHAR(10))
	,'ORDNUNG=' || BSUR.BOTANICSYSTEM_ORDNUNG
	,'FAMILIE=' || BSUR.BOTANICSYSTEM_FAMILIE
	,'UNTERFAMILIE=' || BSUR.BOTANICSYSTEM_UNTERFAMILIE
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER BOTANICSYSTEM_AFTER_DELETE_TRIGGER
	AFTER DELETE ON BOTANICSYSTEM
	REFERENCING OLD AS BSDR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (CURRENT_TIMESTAMP, CURRENT_USER, 'BOTANICSYSTEM', 'Delete Row'
	,'ID=' || CAST (BSDR.BOTANICSYSTEM_ID AS CHAR(10))
	,'VERSION=' || CAST (BSDR.BOTANICSYSTEM_VERSION AS CHAR(10))
	,'ORDINAL=' || CAST (BSDR.BOTANICSYSTEM_ORDINAL AS CHAR(10))
	,'ORDNUNG=' || BSDR.BOTANICSYSTEM_ORDNUNG
	,'FAMILIE=' || BSDR.BOTANICSYSTEM_FAMILIE
	,'UNTERFAMILIE=' || BSDR.BOTANICSYSTEM_UNTERFAMILIE
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER GEOREGION_AFTER_INSERT_TRIGGER
	AFTER INSERT ON GEOREGION
	REFERENCING NEW AS GIR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'GEOREGION', 'Insert Row'
	,'ID=' || CAST (GIR.GEOREGION_ID AS CHAR(10))
	,'VERSION=' || CAST (GIR.GEOREGION_VERSION AS CHAR(10))
	,'ORDINAL=' || CAST (GIR.GEOREGION_ORDINAL AS CHAR(10))
	,'CODE=' || GIR.GEOREGION_CODE
	,'NAME=' || GIR.GEOREGION_NAME
	,'REGION=' || GIR.GEOREGION_REGION
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER GEOREGION_BEFORE_UPDATE_TRIGGER
	AFTER UPDATE ON GEOREGION
	REFERENCING OLD AS GUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'GEOREGION', 'Before Update Row'
	,'ID=' || CAST (GUR.GEOREGION_ID AS CHAR(10))
	,'VERSION=' || CAST (GUR.GEOREGION_VERSION AS CHAR(10))
	,'ORDINAL=' || CAST (GUR.GEOREGION_ORDINAL AS CHAR(10))
	,'CODE=' || GUR.GEOREGION_CODE
	,'NAME=' || GUR.GEOREGION_NAME
	,'REGION=' || GUR.GEOREGION_REGION
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER GEOREGION_AFTER_UPDATE_TRIGGER
	AFTER UPDATE ON GEOREGION
	REFERENCING NEW AS GUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'GEOREGION', 'After Update Row'
	,'ID=' || CAST (GUR.GEOREGION_ID AS CHAR(10))
	,'VERSION=' || CAST (GUR.GEOREGION_VERSION AS CHAR(10))
	,'ORDINAL=' || CAST (GUR.GEOREGION_ORDINAL AS CHAR(10))
	,'CODE=' || GUR.GEOREGION_CODE
	,'NAME=' || GUR.GEOREGION_NAME
	,'REGION=' || GUR.GEOREGION_REGION
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER GEOREGION_AFTER_DELETE_TRIGGER
	AFTER DELETE ON GEOREGION
	REFERENCING OLD AS GDR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (CURRENT_TIMESTAMP, CURRENT_USER, 'GEOREGION', 'Delete Row'
	,'ID=' || CAST (GDR.GEOREGION_ID AS CHAR(10))
	,'VERSION=' || CAST (GDR.GEOREGION_VERSION AS CHAR(10))
	,'ORDINAL=' || CAST (GDR.GEOREGION_ORDINAL AS CHAR(10))
	,'CODE=' || GDR.GEOREGION_CODE
	,'NAME=' || GDR.GEOREGION_NAME
	,'REGION=' || GDR.GEOREGION_REGION
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER ACTOR_AFTER_INSERT_TRIGGER
	AFTER INSERT ON ACTOR
	REFERENCING NEW AS ACIR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'ACTOR', 'Insert Row'
	,'ID=' || CAST (ACIR.ACTOR_ID AS CHAR(10))
	,'VERSION=' || CAST (ACIR.ACTOR_VERSION AS CHAR(10))
	,'USERNAME=' || CAST (ACIR.ACTOR_USERNAME AS CHAR(10))
	,'PWD=' || ACIR.ACTOR_PWD
	,'EMAIL=' || ACIR.ACTOR_EMAIL
	,'GIVENNAME=' || ACIR.ACTOR_GIVENNAME
	,'MIDDLENAME=' || ACIR.ACTOR_MIDDLENAME
	,'FAMILYNAME=' || ACIR.ACTOR_FAMILYNAME
	,'LOGINCOUNT=' || CAST (ACIR.ACTOR_LOGINCOUNT AS CHAR(10))
	,'LOGINFAILED=' || CAST (ACIR.ACTOR_LOGINFAILED AS CHAR(10))
	,'LOCKED=' || CAST(ACIR.ACTOR_LOCKED AS CHAR(05))
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER ACTOR_BEFORE_UPDATE_TRIGGER
	AFTER UPDATE ON ACTOR
	REFERENCING OLD AS ACUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'ACTOR', 'Before Update Row'
	,'ID=' || CAST (ACUR.ACTOR_ID AS CHAR(10))
	,'VERSION=' || CAST (ACUR.ACTOR_VERSION AS CHAR(10))
	,'USERNAME=' || CAST (ACUR.ACTOR_USERNAME AS CHAR(10))
	,'PWD=' || ACUR.ACTOR_PWD
	,'EMAIL=' || ACUR.ACTOR_EMAIL
	,'GIVENNAME=' || ACUR.ACTOR_GIVENNAME
	,'MIDDLENAME=' || ACUR.ACTOR_MIDDLENAME
	,'FAMILYNAME=' || ACUR.ACTOR_FAMILYNAME
	,'LOGINCOUNT=' || CAST (ACUR.ACTOR_LOGINCOUNT AS CHAR(10))
	,'LOGINFAILED=' || CAST (ACUR.ACTOR_LOGINFAILED AS CHAR(10))
	,'LOCKED=' || CAST(ACUR.ACTOR_LOCKED AS CHAR(05))
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER ACTOR_AFTER_UPDATE_TRIGGER
	AFTER UPDATE ON ACTOR
	REFERENCING NEW AS ACUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'ACTOR', 'After Update Row'
	,'ID=' || CAST (ACUR.ACTOR_ID AS CHAR(10))
	,'VERSION=' || CAST (ACUR.ACTOR_VERSION AS CHAR(10))
	,'USERNAME=' || CAST (ACUR.ACTOR_USERNAME AS CHAR(10))
	,'PWD=' || ACUR.ACTOR_PWD
	,'EMAIL=' || ACUR.ACTOR_EMAIL
	,'GIVENNAME=' || ACUR.ACTOR_GIVENNAME
	,'MIDDLENAME=' || ACUR.ACTOR_MIDDLENAME
	,'FAMILYNAME=' || ACUR.ACTOR_FAMILYNAME
	,'LOGINCOUNT=' || CAST (ACUR.ACTOR_LOGINCOUNT AS CHAR(10))
	,'LOGINFAILED=' || CAST (ACUR.ACTOR_LOGINFAILED AS CHAR(10))
	,'LOCKED=' || CAST(ACUR.ACTOR_LOCKED AS CHAR(05))
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER ACTOR_AFTER_DELETE_TRIGGER
	AFTER DELETE ON ACTOR
	REFERENCING OLD AS ACDR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (CURRENT_TIMESTAMP, CURRENT_USER, 'ACTOR', 'Delete Row'
	,'ID=' || CAST (ACDR.ACTOR_ID AS CHAR(10))
	,'VERSION=' || CAST (ACDR.ACTOR_VERSION AS CHAR(10))
	,'USERNAME=' || CAST (ACDR.ACTOR_USERNAME AS CHAR(10))
	,'PWD=' || ACDR.ACTOR_PWD
	,'EMAIL=' || ACDR.ACTOR_EMAIL
	,'GIVENNAME=' || ACDR.ACTOR_GIVENNAME
	,'MIDDLENAME=' || ACDR.ACTOR_MIDDLENAME
	,'FAMILYNAME=' || ACDR.ACTOR_FAMILYNAME
	,'LOGINCOUNT=' || CAST (ACDR.ACTOR_LOGINCOUNT AS CHAR(10))
	,'LOGINFAILED=' || CAST (ACDR.ACTOR_LOGINFAILED AS CHAR(10))
	,'LOCKED=' || CAST(ACDR.ACTOR_LOCKED AS CHAR(05))
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER ACTORROLE_AFTER_INSERT_TRIGGER
	AFTER INSERT ON ACTORROLE
	REFERENCING NEW AS RIR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'ACTORROLE', 'Insert Row'
	,'ID=' || CAST (RIR.ACTORROLE_ID AS CHAR(10))
	,'VERSION=' || CAST (RIR.ACTORROLE_VERSION AS CHAR(10))
	,'NAME=' || RIR.ACTORROLE_NAME
	,'COMMENT=' || RIR.ACTORROLE_COMMENT
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER ACTORROLE_BEFORE_UPDATE_TRIGGER
	AFTER UPDATE ON ACTORROLE
	REFERENCING OLD AS RUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'ACTORROLE', 'Before Update Row'
	,'ID=' || CAST (RUR.ACTORROLE_ID AS CHAR(10))
	,'VERSION=' || CAST (RUR.ACTORROLE_VERSION AS CHAR(10))
	,'NAME=' || RUR.ACTORROLE_NAME
	,'COMMENT=' || RUR.ACTORROLE_COMMENT
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER ACTORROLE_AFTER_UPDATE_TRIGGER
	AFTER UPDATE ON ACTORROLE
	REFERENCING NEW AS RUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'ACTORROLE', 'After Update Row'
	,'ID=' || CAST (RUR.ACTORROLE_ID AS CHAR(10))
	,'VERSION=' || CAST (RUR.ACTORROLE_VERSION AS CHAR(10))
	,'NAME=' || RUR.ACTORROLE_NAME
	,'COMMENT=' || RUR.ACTORROLE_COMMENT
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER ACTORROLE_AFTER_DELETE_TRIGGER
	AFTER DELETE ON ACTORROLE
	REFERENCING OLD AS RDR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (CURRENT_TIMESTAMP, CURRENT_USER, 'ACTORROLE', 'Delete Row'
	,'ID=' || CAST (RDR.ACTORROLE_ID AS CHAR(10))
	,'VERSION=' || CAST (RDR.ACTORROLE_VERSION AS CHAR(10))
	,'NAME=' || RDR.ACTORROLE_NAME
	,'COMMENT=' || RDR.ACTORROLE_COMMENT
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER ACTORSESSION_AFTER_INSERT_TRIGGER
	AFTER INSERT ON ACTORSESSION
	REFERENCING NEW AS ASIR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'ACTORSESSION', 'Insert Row'
	,'ID=' || CAST (ASIR.ACTORSESSION_ID AS CHAR(10))
	,'VERSION=' || CAST (ASIR.ACTORSESSION_VERSION AS CHAR(10))
	,'ACTOR_ID=' || CAST (ASIR.ACTORSESSION_ACTOR_ID AS CHAR(10))
	,'LOGIN=' || CAST (ASIR.ACTORSESSION_LOGIN AS CHAR(28))
	,'LOGOUT=' || CAST (ASIR.ACTORSESSION_LOGOUT AS CHAR(28))
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER ACTORSESSION_BEFORE_UPDATE_TRIGGER
	AFTER UPDATE ON ACTORSESSION
	REFERENCING OLD AS ASUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'ACTORSESSION', 'Before Update Row'
	,'ID=' || CAST (ASUR.ACTORSESSION_ID AS CHAR(10))
	,'VERSION=' || CAST (ASUR.ACTORSESSION_VERSION AS CHAR(10))
	,'ACTOR_ID=' || CAST (ASUR.ACTORSESSION_ACTOR_ID AS CHAR(10))
	,'LOGIN=' || CAST (ASUR.ACTORSESSION_LOGIN AS CHAR(28))
	,'LOGOUT=' || CAST (ASUR.ACTORSESSION_LOGOUT AS CHAR(28))
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER ACTORSESSION_AFTER_UPDATE_TRIGGER
	AFTER UPDATE ON ACTORSESSION
	REFERENCING NEW AS ASUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'ACTORSESSION', 'After Update Row'
	,'ID=' || CAST (ASUR.ACTORSESSION_ID AS CHAR(10))
	,'VERSION=' || CAST (ASUR.ACTORSESSION_VERSION AS CHAR(10))
	,'ACTOR_ID=' || CAST (ASUR.ACTORSESSION_ACTOR_ID AS CHAR(10))
	,'LOGIN=' || CAST (ASUR.ACTORSESSION_LOGIN AS CHAR(28))
	,'LOGOUT=' || CAST (ASUR.ACTORSESSION_LOGOUT AS CHAR(28))
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER ACTORSESSION_AFTER_DELETE_TRIGGER
	AFTER DELETE ON ACTORSESSION
	REFERENCING OLD AS ASDR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (CURRENT_TIMESTAMP, CURRENT_USER, 'ACTORSESSION', 'Delete Row'
	,'ID=' || CAST (ASDR.ACTORSESSION_ID AS CHAR(10))
	,'VERSION=' || CAST (ASDR.ACTORSESSION_VERSION AS CHAR(10))
	,'ACTOR_ID=' || CAST (ASDR.ACTORSESSION_ACTOR_ID AS CHAR(10))
	,'LOGIN=' || CAST (ASDR.ACTORSESSION_LOGIN AS CHAR(28))
	,'LOGOUT=' || CAST (ASDR.ACTORSESSION_LOGOUT AS CHAR(28))
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER ACTORIDENTITY_AFTER_INSERT_TRIGGER
	AFTER INSERT ON ACTORIDENTITY
	REFERENCING NEW AS AIIR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'ACTORIDENTITY', 'Insert Row'
	,'ROLE_ID=' || CAST (AIIR.ROLE_ID AS CHAR(10))
	,'ACTOR_ID=' || CAST (AIIR.ACTOR_ID AS CHAR(10))
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER ACTORIDENTITY_BEFORE_UPDATE_TRIGGER
	AFTER UPDATE ON ACTORIDENTITY
	REFERENCING OLD AS AIUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'ACTORIDENTITY', 'Before Update Row'
	,'ROLE_ID=' || CAST (AIUR.ROLE_ID AS CHAR(10))
	,'ACTOR_ID=' || CAST (AIUR.ACTOR_ID AS CHAR(10))
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER ACTORIDENTITY_AFTER_UPDATE_TRIGGER
	AFTER UPDATE ON ACTORIDENTITY
	REFERENCING NEW AS AIUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'ACTORIDENTITY', 'After Update Row'
	,'ROLE_ID=' || CAST (AIUR.ROLE_ID AS CHAR(10))
	,'ACTOR_ID=' || CAST (AIUR.ACTOR_ID AS CHAR(10))
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER ACTORIDENTITY_AFTER_DELETE_TRIGGER
	AFTER DELETE ON ACTORIDENTITY
	REFERENCING OLD AS AIDR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (CURRENT_TIMESTAMP, CURRENT_USER, 'ACTORIDENTITY', 'Delete Row'
	,'ROLE_ID=' || CAST (AIDR.ROLE_ID AS CHAR(10))
	,'ACTOR_ID=' || CAST (AIDR.ACTOR_ID AS CHAR(10))
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER STATUS_AFTER_INSERT_TRIGGER
	AFTER INSERT ON STATUS
	REFERENCING NEW AS SIR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'STATUS', 'Insert Row'
	,'ID=' || CAST (SIR.STATUS_ID AS CHAR(10))
	,'VERSION=' || CAST (SIR.STATUS_VERSION AS CHAR(10))
	,'TEXT=' || SIR.STATUS_TEXT
	,'COMMENT=' || SIR.STATUS_COMMENT
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER STATUS_BEFORE_UPDATE_TRIGGER
	AFTER UPDATE ON STATUS
	REFERENCING OLD AS SUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'STATUS', 'Before Update Row'
	,'ID=' || CAST (SUR.STATUS_ID AS CHAR(10))
	,'VERSION=' || CAST (SUR.STATUS_VERSION AS CHAR(10))
	,'TEXT=' || SUR.STATUS_TEXT
	,'COMMENT=' || SUR.STATUS_COMMENT
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER STATUS_AFTER_UPDATE_TRIGGER
	AFTER UPDATE ON STATUS
	REFERENCING NEW AS SUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'STATUS', 'After Update Row'
	,'ID=' || CAST (SUR.STATUS_ID AS CHAR(10))
	,'VERSION=' || CAST (SUR.STATUS_VERSION AS CHAR(10))
	,'TEXT=' || SUR.STATUS_TEXT
	,'COMMENT=' || SUR.STATUS_COMMENT
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER STATUS_AFTER_DELETE_TRIGGER
	AFTER DELETE ON STATUS
	REFERENCING OLD AS SDR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (CURRENT_TIMESTAMP, CURRENT_USER, 'STATUS', 'Delete Row'
	,'ID=' || CAST (SDR.STATUS_ID AS CHAR(10))
	,'VERSION=' || CAST (SDR.STATUS_VERSION AS CHAR(10))
	,'TEXT=' || SDR.STATUS_TEXT
	,'COMMENT=' || SDR.STATUS_COMMENT
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER TIMBER_AFTER_INSERT_TRIGGER
	AFTER INSERT ON TIMBER
	REFERENCING NEW AS TIR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'TIMBER', 'Insert Row'
	,'ID=' || CAST (TIR.TIMBER_ID AS CHAR(10))
	,'VERSION=' || CAST (TIR.TIMBER_VERSION AS CHAR(10))
	,'GEOREGION_ID=' || CAST (TIR.TIMBER_GEOREGION_ID AS CHAR(10))
	,'BOTANICSYSTEM_ID=' || CAST (TIR.TIMBER_BOTANICSYSTEM_ID AS CHAR(10))
	,'TYPE=' || TIR.TIMBER_TYPE
	,'CODE=' || TIR.TIMBER_CODE
	,'NAME=' || TIR.TIMBER_NAME
	,'IMAGENAME=' || TIR.TIMBER_IMAGENAME
	,'AKADEMISCHERNAME=' || TIR.TIMBER_AKADEMISCHERNAME
	,'ROHDICHTE=' || CAST (TIR.TIMBER_ROHDICHTE AS CHAR(15))
	,'ZUGFESTIGKEIT=' || CAST (TIR.TIMBER_ZUGFESTIGKEIT AS CHAR(10))
	,'DRUCKFESTIGKEIT=' || CAST(TIR.TIMBER_DRUCKFESTIGKEIT AS CHAR(15))
	,'BIEGEFESTIGKEIT=' || CAST(TIR.TIMBER_BIEGEFESTIGKEIT AS CHAR(15))
	,'SCHERFESTIGKEIT=' || CAST(TIR.TIMBER_SCHERFESTIGKEIT AS CHAR(15))
	,'BRINELL_HAERTE1=' || CAST(TIR.TIMBER_BRINELL_HAERTE1 AS CHAR(15))
	,'BRINELL_HAERTE2=' || CAST(TIR.TIMBER_BRINELL_HAERTE2 AS CHAR(15))
	,'TANGENTIALSCHWUND=' || CAST(TIR.TIMBER_TANGENTIALSCHWUND AS CHAR(15))
	,'RADIALSCHWUND=' || CAST(TIR.TIMBER_RADIALSCHWUND AS CHAR(15))
	,''
	,''
	);

CREATE TRIGGER TIMBER_BEFORE_UPDATE_TRIGGER
	AFTER UPDATE ON TIMBER
	REFERENCING OLD AS TUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'TIMBER', 'Before Update Row'
	,'ID=' || CAST (TUR.TIMBER_ID AS CHAR(10))
	,'VERSION=' || CAST (TUR.TIMBER_VERSION AS CHAR(10))
	,'GEOREGION_ID=' || CAST (TUR.TIMBER_GEOREGION_ID AS CHAR(10))
	,'BOTANICSYSTEM_ID=' || CAST (TUR.TIMBER_BOTANICSYSTEM_ID AS CHAR(10))
	,'TYPE=' || TUR.TIMBER_TYPE
	,'CODE=' || TUR.TIMBER_CODE
	,'NAME=' || TUR.TIMBER_NAME
	,'IMAGENAME=' || TUR.TIMBER_IMAGENAME
	,'AKADEMISCHERNAME=' || TUR.TIMBER_AKADEMISCHERNAME
	,'ROHDICHTE=' || CAST (TUR.TIMBER_ROHDICHTE AS CHAR(15))
	,'ZUGFESTIGKEIT=' || CAST (TUR.TIMBER_ZUGFESTIGKEIT AS CHAR(10))
	,'DRUCKFESTIGKEIT=' || CAST(TUR.TIMBER_DRUCKFESTIGKEIT AS CHAR(15))
	,'BIEGEFESTIGKEIT=' || CAST(TUR.TIMBER_BIEGEFESTIGKEIT AS CHAR(15))
	,'SCHERFESTIGKEIT=' || CAST(TUR.TIMBER_SCHERFESTIGKEIT AS CHAR(15))
	,'BRINELL_HAERTE1=' || CAST(TUR.TIMBER_BRINELL_HAERTE1 AS CHAR(15))
	,'BRINELL_HAERTE2=' || CAST(TUR.TIMBER_BRINELL_HAERTE2 AS CHAR(15))
	,'TANGENTIALSCHWUND=' || CAST(TUR.TIMBER_TANGENTIALSCHWUND AS CHAR(15))
	,'RADIALSCHWUND=' || CAST(TUR.TIMBER_RADIALSCHWUND AS CHAR(15))
	,''
	,''
	);

CREATE TRIGGER TIMBER_AFTER_UPDATE_TRIGGER
	AFTER UPDATE ON TIMBER
	REFERENCING NEW AS TUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'TIMBER', 'After Update Row'
	,'ID=' || CAST (TUR.TIMBER_ID AS CHAR(10))
	,'VERSION=' || CAST (TUR.TIMBER_VERSION AS CHAR(10))
	,'GEOREGION_ID=' || CAST (TUR.TIMBER_GEOREGION_ID AS CHAR(10))
	,'BOTANICSYSTEM_ID=' || CAST (TUR.TIMBER_BOTANICSYSTEM_ID AS CHAR(10))
	,'TYPE=' || TUR.TIMBER_TYPE
	,'CODE=' || TUR.TIMBER_CODE
	,'NAME=' || TUR.TIMBER_NAME
	,'IMAGENAME=' || TUR.TIMBER_IMAGENAME
	,'AKADEMISCHERNAME=' || TUR.TIMBER_AKADEMISCHERNAME
	,'ROHDICHTE=' || CAST (TUR.TIMBER_ROHDICHTE AS CHAR(15))
	,'ZUGFESTIGKEIT=' || CAST (TUR.TIMBER_ZUGFESTIGKEIT AS CHAR(10))
	,'DRUCKFESTIGKEIT=' || CAST(TUR.TIMBER_DRUCKFESTIGKEIT AS CHAR(15))
	,'BIEGEFESTIGKEIT=' || CAST(TUR.TIMBER_BIEGEFESTIGKEIT AS CHAR(15))
	,'SCHERFESTIGKEIT=' || CAST(TUR.TIMBER_SCHERFESTIGKEIT AS CHAR(15))
	,'BRINELL_HAERTE1=' || CAST(TUR.TIMBER_BRINELL_HAERTE1 AS CHAR(15))
	,'BRINELL_HAERTE2=' || CAST(TUR.TIMBER_BRINELL_HAERTE2 AS CHAR(15))
	,'TANGENTIALSCHWUND=' || CAST(TUR.TIMBER_TANGENTIALSCHWUND AS CHAR(15))
	,'RADIALSCHWUND=' || CAST(TUR.TIMBER_RADIALSCHWUND AS CHAR(15))
	,''
	,''
	);

CREATE TRIGGER TIMBER_AFTER_DELETE_TRIGGER
	AFTER DELETE ON TIMBER
	REFERENCING OLD AS TDR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (CURRENT_TIMESTAMP, CURRENT_USER, 'TIMBER', 'Delete Row'
	,'ID=' || CAST (TDR.TIMBER_ID AS CHAR(10))
	,'VERSION=' || CAST (TDR.TIMBER_VERSION AS CHAR(10))
	,'GEOREGION_ID=' || CAST (TDR.TIMBER_GEOREGION_ID AS CHAR(10))
	,'BOTANICSYSTEM_ID=' || CAST (TDR.TIMBER_BOTANICSYSTEM_ID AS CHAR(10))
	,'TYPE=' || TDR.TIMBER_TYPE
	,'CODE=' || TDR.TIMBER_CODE
	,'NAME=' || TDR.TIMBER_NAME
	,'IMAGENAME=' || TDR.TIMBER_IMAGENAME
	,'AKADEMISCHERNAME=' || TDR.TIMBER_AKADEMISCHERNAME
	,'ROHDICHTE=' || CAST (TDR.TIMBER_ROHDICHTE AS CHAR(15))
	,'ZUGFESTIGKEIT=' || CAST (TDR.TIMBER_ZUGFESTIGKEIT AS CHAR(10))
	,'DRUCKFESTIGKEIT=' || CAST(TDR.TIMBER_DRUCKFESTIGKEIT AS CHAR(15))
	,'BIEGEFESTIGKEIT=' || CAST(TDR.TIMBER_BIEGEFESTIGKEIT AS CHAR(15))
	,'SCHERFESTIGKEIT=' || CAST(TDR.TIMBER_SCHERFESTIGKEIT AS CHAR(15))
	,'BRINELL_HAERTE1=' || CAST(TDR.TIMBER_BRINELL_HAERTE1 AS CHAR(15))
	,'BRINELL_HAERTE2=' || CAST(TDR.TIMBER_BRINELL_HAERTE2 AS CHAR(15))
	,'TANGENTIALSCHWUND=' || CAST(TDR.TIMBER_TANGENTIALSCHWUND AS CHAR(15))
	,'RADIALSCHWUND=' || CAST(TDR.TIMBER_RADIALSCHWUND AS CHAR(15))
	,''
	,''
	);

CREATE TRIGGER MODIFICATION_AFTER_INSERT_TRIGGER
	AFTER INSERT ON MODIFICATION
	REFERENCING NEW AS MIR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'MODIFICATION', 'Insert Row'
	,'ID=' || CAST (MIR.MODIFICATION_ID AS CHAR(10))
	,'VERSION=' || CAST (MIR.MODIFICATION_VERSION AS CHAR(10))
	,'ARTEFACT_ID=' || CAST (MIR.MODIFICATION_ARTEFACT_ID AS CHAR(10))
	,'MODSTEP_ID=' || CAST (MIR.MODIFICATION_MODSTEP_ID AS CHAR(10))
	,'DATE=' || CAST (MIR.MODIFICATION_DATE AS CHAR(10))
	,'DIAMETER=' || CAST(MIR.MODIFICATION_DIAMETER AS CHAR(10))
	,'HEIGHT=' || CAST (MIR.MODIFICATION_HEIGHT AS CHAR(10))
	,'WALLTHICKNESS_MIN=' || CAST (MIR.MODIFICATION_WALLTHICKNESS_MIN AS CHAR(10))
	,'WALLTHICKNESS_MAX=' || CAST (MIR.MODIFICATION_WALLTHICKNESS_MAX AS CHAR(10))
	,'GRANULATION=' || CAST (MIR.MODIFICATION_GRANULATION AS CHAR(10))
	,'TAP' || CAST(MIR.MODIFICATION_TAP AS CHAR(10))
	,'RECESS=' || CAST(MIR.MODIFICATION_RECESS AS CHAR(10))
	,'SURFACE=' || MIR.MODIFICATION_SURFACE
	,'COMMENT=' || MIR.MODIFICATION_COMMENT
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER MODIFICATION_BEFORE_UPDATE_TRIGGER
	AFTER UPDATE ON MODIFICATION
	REFERENCING OLD AS MUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'MODIFICATION', 'Before Update Row'
	,'ID=' || CAST (MUR.MODIFICATION_ID AS CHAR(10))
	,'VERSION=' || CAST (MUR.MODIFICATION_VERSION AS CHAR(10))
	,'ARTEFACT_ID=' || CAST (MUR.MODIFICATION_ARTEFACT_ID AS CHAR(10))
	,'MODSTEP_ID=' || CAST (MUR.MODIFICATION_MODSTEP_ID AS CHAR(10))
	,'DATE=' || CAST (MUR.MODIFICATION_DATE AS CHAR(10))
	,'DIAMETER=' || CAST(MUR.MODIFICATION_DIAMETER AS CHAR(10))
	,'HEIGHT=' || CAST (MUR.MODIFICATION_HEIGHT AS CHAR(10))
	,'WALLTHICKNESS_MIN=' || CAST (MUR.MODIFICATION_WALLTHICKNESS_MIN AS CHAR(10))
	,'WALLTHICKNESS_MAX=' || CAST (MUR.MODIFICATION_WALLTHICKNESS_MAX AS CHAR(10))
	,'GRANULATION=' || CAST (MUR.MODIFICATION_GRANULATION AS CHAR(10))
	,'TAP' || CAST(MUR.MODIFICATION_TAP AS CHAR(10))
	,'RECESS=' || CAST(MUR.MODIFICATION_RECESS AS CHAR(10))
	,'SURFACE=' || MUR.MODIFICATION_SURFACE
	,'COMMENT=' || MUR.MODIFICATION_COMMENT
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER MODIFICATION_AFTER_UPDATE_TRIGGER
	AFTER UPDATE ON MODIFICATION
	REFERENCING NEW AS MUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'MODIFICATION', 'After Update Row'
	,'ID=' || CAST (MUR.MODIFICATION_ID AS CHAR(10))
	,'VERSION=' || CAST (MUR.MODIFICATION_VERSION AS CHAR(10))
	,'ARTEFACT_ID=' || CAST (MUR.MODIFICATION_ARTEFACT_ID AS CHAR(10))
	,'MODSTEP_ID=' || CAST (MUR.MODIFICATION_MODSTEP_ID AS CHAR(10))
	,'DATE=' || CAST (MUR.MODIFICATION_DATE AS CHAR(10))
	,'DIAMETER=' || CAST(MUR.MODIFICATION_DIAMETER AS CHAR(10))
	,'HEIGHT=' || CAST (MUR.MODIFICATION_HEIGHT AS CHAR(10))
	,'WALLTHICKNESS_MIN=' || CAST (MUR.MODIFICATION_WALLTHICKNESS_MIN AS CHAR(10))
	,'WALLTHICKNESS_MAX=' || CAST (MUR.MODIFICATION_WALLTHICKNESS_MAX AS CHAR(10))
	,'GRANULATION=' || CAST (MUR.MODIFICATION_GRANULATION AS CHAR(10))
	,'TAP' || CAST(MUR.MODIFICATION_TAP AS CHAR(10))
	,'RECESS=' || CAST(MUR.MODIFICATION_RECESS AS CHAR(10))
	,'SURFACE=' || MUR.MODIFICATION_SURFACE
	,'COMMENT=' || MUR.MODIFICATION_COMMENT
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER MODIFICATION_AFTER_DELETE_TRIGGER
	AFTER DELETE ON MODIFICATION
	REFERENCING OLD AS MDR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (CURRENT_TIMESTAMP, CURRENT_USER, 'MODIFICATION', 'Delete Row'
	,'ID=' || CAST (MDR.MODIFICATION_ID AS CHAR(10))
	,'VERSION=' || CAST (MDR.MODIFICATION_VERSION AS CHAR(10))
	,'ARTEFACT_ID=' || CAST (MDR.MODIFICATION_ARTEFACT_ID AS CHAR(10))
	,'MODSTEP_ID=' || CAST (MDR.MODIFICATION_MODSTEP_ID AS CHAR(10))
	,'DATE=' || CAST (MDR.MODIFICATION_DATE AS CHAR(10))
	,'DIAMETER=' || CAST(MDR.MODIFICATION_DIAMETER AS CHAR(10))
	,'HEIGHT=' || CAST (MDR.MODIFICATION_HEIGHT AS CHAR(10))
	,'WALLTHICKNESS_MIN=' || CAST (MDR.MODIFICATION_WALLTHICKNESS_MIN AS CHAR(10))
	,'WALLTHICKNESS_MAX=' || CAST (MDR.MODIFICATION_WALLTHICKNESS_MAX AS CHAR(10))
	,'GRANULATION=' || CAST (MDR.MODIFICATION_GRANULATION AS CHAR(15))
	,'TAP' || CAST(MDR.MODIFICATION_TAP AS CHAR(15))
	,'RECESS=' || CAST(MDR.MODIFICATION_RECESS AS CHAR(15))
	,'SURFACE=' ||MDR.MODIFICATION_SURFACE
	,'COMMENT=' || MDR.MODIFICATION_COMMENT
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER MODSTEP_AFTER_INSERT_TRIGGER
	AFTER INSERT ON MODSTEP
	REFERENCING NEW AS MSIR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'MODSTEP', 'Insert Row'
	,'ID=' || CAST (MSIR.MODSTEP_ID AS CHAR(10))
	,'VERSION=' || CAST (MSIR.MODSTEP_VERSION AS CHAR(10))
	,'NAME=' || MSIR.MODSTEP_NAME
	,'COMMENT=' || MSIR.MODSTEP_COMMENT
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER MODSTEP_BEFORE_UPDATE_TRIGGER
	AFTER UPDATE ON MODSTEP
	REFERENCING OLD AS MSUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'MODSTEP', 'Before Update Row'
	,'ID=' || CAST (MSUR.MODSTEP_ID AS CHAR(10))
	,'VERSION=' || CAST (MSUR.MODSTEP_VERSION AS CHAR(10))
	,'NAME=' || MSUR.MODSTEP_NAME
	,'COMMENT=' || MSUR.MODSTEP_COMMENT
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER MODSTEP_AFTER_UPDATE_TRIGGER
	AFTER UPDATE ON MODSTEP
	REFERENCING NEW AS MSUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'MODSTEP', 'After Update Row'
	,'ID=' || CAST (MSUR.MODSTEP_ID AS CHAR(10))
	,'VERSION=' || CAST (MSUR.MODSTEP_VERSION AS CHAR(10))
	,'NAME=' || MSUR.MODSTEP_NAME
	,'COMMENT=' || MSUR.MODSTEP_COMMENT
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER MODSTEP_AFTER_DELETE_TRIGGER
	AFTER DELETE ON MODSTEP
	REFERENCING OLD AS MSDR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (CURRENT_TIMESTAMP, CURRENT_USER, 'MODSTEP', 'Delete Row'
	,'ID=' || CAST (MSDR.MODSTEP_ID AS CHAR(10))
	,'VERSION=' || CAST (MSDR.MODSTEP_VERSION AS CHAR(10))
	,'NAME=' || MSDR.MODSTEP_NAME
	,'COMMENT=' || MSDR.MODSTEP_COMMENT
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER MODPROCESS_AFTER_INSERT_TRIGGER
	AFTER INSERT ON MODPROCESS
	REFERENCING NEW AS MPIR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'MODPROCESS', 'Insert Row'
	,'ID=' || CAST (MPIR.MODPROCESS_ID AS CHAR(10))
	,'VERSION=' || CAST (MPIR.MODPROCESS_VERSION AS CHAR(10))
	,'MODIFICATION_ID=' || CAST (MPIR.MODPROCESS_MODIFICATION_ID AS CHAR(10))
	,'DATE=' || CAST (MPIR.MODPROCESS_DATE AS CHAR(10))
	,'WEIGHT=' || CAST (MPIR.MODPROCESS_WEIGHT AS CHAR(10))
	,'MOISTURE=' || CAST (MPIR.MODPROCESS_MOISTURE AS CHAR(10))
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER MODPROCESS_BEFORE_UPDATE_TRIGGER
	AFTER UPDATE ON MODPROCESS
	REFERENCING OLD AS MPUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'MODPROCESS', 'Before Update Row'
	,'ID=' || CAST (MPUR.MODPROCESS_ID AS CHAR(10))
	,'VERSION=' || CAST (MPUR.MODPROCESS_VERSION AS CHAR(10))
	,'MODIFICATION_ID=' || CAST (MPUR.MODPROCESS_MODIFICATION_ID AS CHAR(10))
	,'DATE=' || CAST (MPUR.MODPROCESS_DATE AS CHAR(10))
	,'WEIGHT=' || CAST (MPUR.MODPROCESS_WEIGHT AS CHAR(10))
	,'MOISTURE=' || CAST (MPUR.MODPROCESS_MOISTURE AS CHAR(10))
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER MODPROCESS_AFTER_UPDATE_TRIGGER
	AFTER UPDATE ON MODPROCESS
	REFERENCING NEW AS MPUR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (
	 CURRENT_TIMESTAMP, CURRENT_USER, 'MODPROCESS', 'After Update Row'
	,'ID=' || CAST (MPUR.MODPROCESS_ID AS CHAR(10))
	,'VERSION=' || CAST (MPUR.MODPROCESS_VERSION AS CHAR(10))
	,'MODIFICATION_ID=' || CAST (MPUR.MODPROCESS_MODIFICATION_ID AS CHAR(10))
	,'DATE=' || CAST (MPUR.MODPROCESS_DATE AS CHAR(10))
	,'WEIGHT=' || CAST (MPUR.MODPROCESS_WEIGHT AS CHAR(10))
	,'MOISTURE=' || CAST (MPUR.MODPROCESS_MOISTURE AS CHAR(10))
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

CREATE TRIGGER MODPROCESS_AFTER_DELETE_TRIGGER
	AFTER DELETE ON MODPROCESS
	REFERENCING OLD AS MPDR
	FOR EACH ROW -- STATEMENT
	INSERT INTO AUDIT (AUDIT_TIMESTAMP, AUDIT_USER, AUDIT_TABLE, AUDIT_ACTION,
	AUDIT_FIELD01, AUDIT_FIELD02, AUDIT_FIELD03, AUDIT_FIELD04,	AUDIT_FIELD05, AUDIT_FIELD06, AUDIT_FIELD07, AUDIT_FIELD08, AUDIT_FIELD09, AUDIT_FIELD10,
	AUDIT_FIELD11, AUDIT_FIELD12, AUDIT_FIELD13, AUDIT_FIELD14, AUDIT_FIELD15, AUDIT_FIELD16, AUDIT_FIELD17, AUDIT_FIELD18, AUDIT_FIELD19, AUDIT_FIELD20)
	VALUES (CURRENT_TIMESTAMP, CURRENT_USER, 'MODPROCESS', 'Delete Row'
	,'ID=' || CAST (MPDR.MODPROCESS_ID AS CHAR(10))
	,'VERSION=' || CAST (MPDR.MODPROCESS_VERSION AS CHAR(10))
	,'MODIFICATION_ID=' || CAST (MPDR.MODPROCESS_MODIFICATION_ID AS CHAR(10))
	,'DATE=' || CAST (MPDR.MODPROCESS_DATE AS CHAR(10))
	,'WEIGHT=' || CAST (MPDR.MODPROCESS_WEIGHT AS CHAR(10))
	,'MOISTURE=' || CAST (MPDR.MODPROCESS_MOISTURE AS CHAR(10))
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	,''
	);

--COMMIT;


