-- ==================================================
-- Set AUTOCOMMIT OFF
-- ==================================================
--SET AUTOCOMMIT OFF;

-- ==================================================
-- Trigger: DROP Triggers
-- ==================================================
DROP TRIGGER ARTEFACT_AFTER_INSERT_TRIGGER;
DROP TRIGGER ARTEFACT_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER ARTEFACT_AFTER_UPDATE_TRIGGER;
DROP TRIGGER ARTEFACT_AFTER_DELETE_TRIGGER;

DROP TRIGGER BOTANICSYSTEM_AFTER_INSERT_TRIGGER;
DROP TRIGGER BOTANICSYSTEM_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER BOTANICSYSTEM_AFTER_UPDATE_TRIGGER;
DROP TRIGGER BOTANICSYSTEM_AFTER_DELETE_TRIGGER;

DROP TRIGGER GEOREGION_AFTER_INSERT_TRIGGER;
DROP TRIGGER GEOREGION_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER GEOREGION_AFTER_UPDATE_TRIGGER;
DROP TRIGGER GEOREGION_AFTER_DELETE_TRIGGER;

DROP TRIGGER ACTOR_AFTER_INSERT_TRIGGER;
DROP TRIGGER ACTOR_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER ACTOR_AFTER_UPDATE_TRIGGER;
DROP TRIGGER ACTOR_AFTER_DELETE_TRIGGER;

DROP TRIGGER ACTORROLE_AFTER_INSERT_TRIGGER;
DROP TRIGGER ACTORROLE_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER ACTORROLE_AFTER_UPDATE_TRIGGER;
DROP TRIGGER ACTORROLE_AFTER_DELETE_TRIGGER;

DROP TRIGGER ACTORSESSION_AFTER_INSERT_TRIGGER;
DROP TRIGGER ACTORSESSION_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER ACTORSESSION_AFTER_UPDATE_TRIGGER;
DROP TRIGGER ACTORSESSION_AFTER_DELETE_TRIGGER;

DROP TRIGGER ACTORIDENTITY_AFTER_INSERT_TRIGGER;
DROP TRIGGER ACTORIDENTITY_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER ACTORIDENTITY_AFTER_UPDATE_TRIGGER;
DROP TRIGGER ACTORIDENTITY_AFTER_DELETE_TRIGGER;

DROP TRIGGER STATUS_AFTER_INSERT_TRIGGER;
DROP TRIGGER STATUS_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER STATUS_AFTER_UPDATE_TRIGGER;
DROP TRIGGER STATUS_AFTER_DELETE_TRIGGER;

DROP TRIGGER TIMBER_AFTER_INSERT_TRIGGER;
DROP TRIGGER TIMBER_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER TIMBER_AFTER_UPDATE_TRIGGER;
DROP TRIGGER TIMBER_AFTER_DELETE_TRIGGER;

DROP TRIGGER MODIFICATION_AFTER_INSERT_TRIGGER;
DROP TRIGGER MODIFICATION_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER MODIFICATION_AFTER_UPDATE_TRIGGER;
DROP TRIGGER MODIFICATION_AFTER_DELETE_TRIGGER;

DROP TRIGGER MODSTEP_AFTER_INSERT_TRIGGER;
DROP TRIGGER MODSTEP_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER MODSTEP_AFTER_UPDATE_TRIGGER;
DROP TRIGGER MODSTEP_AFTER_DELETE_TRIGGER;

DROP TRIGGER MODPROCESS_AFTER_INSERT_TRIGGER;
DROP TRIGGER MODPROCESS_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER MODPROCESS_AFTER_UPDATE_TRIGGER;
DROP TRIGGER MODPROCESS_AFTER_DELETE_TRIGGER;

--COMMIT;