-- ==================================================
-- Set AUTOCOMMIT OFF
-- ==================================================
--SET AUTOCOMMIT OFF;

-- ==================================================
-- Trigger: DROP Triggers
-- ==================================================
DROP TRIGGER SUB.ARTEFACT_AFTER_INSERT_TRIGGER;
DROP TRIGGER SUB.ARTEFACT_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER SUB.ARTEFACT_AFTER_UPDATE_TRIGGER;
DROP TRIGGER SUB.ARTEFACT_AFTER_DELETE_TRIGGER;

DROP TRIGGER SUB.BOTANICSYSTEM_AFTER_INSERT_TRIGGER;
DROP TRIGGER SUB.BOTANICSYSTEM_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER SUB.BOTANICSYSTEM_AFTER_UPDATE_TRIGGER;
DROP TRIGGER SUB.BOTANICSYSTEM_AFTER_DELETE_TRIGGER;

DROP TRIGGER SUB.GEOREGION_AFTER_INSERT_TRIGGER;
DROP TRIGGER SUB.GEOREGION_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER SUB.GEOREGION_AFTER_UPDATE_TRIGGER;
DROP TRIGGER SUB.GEOREGION_AFTER_DELETE_TRIGGER;

DROP TRIGGER SUB.ACTOR_AFTER_INSERT_TRIGGER;
DROP TRIGGER SUB.ACTOR_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER SUB.ACTOR_AFTER_UPDATE_TRIGGER;
DROP TRIGGER SUB.ACTOR_AFTER_DELETE_TRIGGER;

DROP TRIGGER SUB.ACTORROLE_AFTER_INSERT_TRIGGER;
DROP TRIGGER SUB.ACTORROLE_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER SUB.ACTORROLE_AFTER_UPDATE_TRIGGER;
DROP TRIGGER SUB.ACTORROLE_AFTER_DELETE_TRIGGER;

DROP TRIGGER SUB.ACTORSESSION_AFTER_INSERT_TRIGGER;
DROP TRIGGER SUB.ACTORSESSION_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER SUB.ACTORSESSION_AFTER_UPDATE_TRIGGER;
DROP TRIGGER SUB.ACTORSESSION_AFTER_DELETE_TRIGGER;

DROP TRIGGER SUB.ACTORIDENTITY_AFTER_INSERT_TRIGGER;
DROP TRIGGER SUB.ACTORIDENTITY_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER SUB.ACTORIDENTITY_AFTER_UPDATE_TRIGGER;
DROP TRIGGER SUB.ACTORIDENTITY_AFTER_DELETE_TRIGGER;

DROP TRIGGER SUB.STATUS_AFTER_INSERT_TRIGGER;
DROP TRIGGER SUB.STATUS_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER SUB.STATUS_AFTER_UPDATE_TRIGGER;
DROP TRIGGER SUB.STATUS_AFTER_DELETE_TRIGGER;

DROP TRIGGER SUB.TIMBER_AFTER_INSERT_TRIGGER;
DROP TRIGGER SUB.TIMBER_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER SUB.TIMBER_AFTER_UPDATE_TRIGGER;
DROP TRIGGER SUB.TIMBER_AFTER_DELETE_TRIGGER;

DROP TRIGGER SUB.MODIFICATION_AFTER_INSERT_TRIGGER;
DROP TRIGGER SUB.MODIFICATION_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER SUB.MODIFICATION_AFTER_UPDATE_TRIGGER;
DROP TRIGGER SUB.MODIFICATION_AFTER_DELETE_TRIGGER;

DROP TRIGGER SUB.MODSTEP_AFTER_INSERT_TRIGGER;
DROP TRIGGER SUB.MODSTEP_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER SUB.MODSTEP_AFTER_UPDATE_TRIGGER;
DROP TRIGGER SUB.MODSTEP_AFTER_DELETE_TRIGGER;

DROP TRIGGER SUB.MODPROCESS_AFTER_INSERT_TRIGGER;
DROP TRIGGER SUB.MODPROCESS_BEFORE_UPDATE_TRIGGER;
DROP TRIGGER SUB.MODPROCESS_AFTER_UPDATE_TRIGGER;
DROP TRIGGER SUB.MODPROCESS_AFTER_DELETE_TRIGGER;

--COMMIT;