-- ==================================================
-- Table: AUDIT
-- ==================================================
DELETE FROM SUB.AUDIT;

SELECT * FROM SUB.AUDIT;

-- ==================================================
-- Table: MODROLE
-- ==================================================
INSERT INTO SUB.MODROLE (ROLE_VERSION, ROLE_NAME, ROLE_DESCRIPTION) VALUES
	 (0, 'test', 'Tester');

INSERT INTO SUB.STATUS (STATUS_VERSION, STATUS_BEZEICHNUNG)
VALUES
	 (0, 'in Reparatur');

DELETE FROM SUB.ROLE r WHERE r.ROLE_ID = 6;

DELETE FROM SUB.STATUS s WHERE s.STATUS_ID = 8;

-- ==================================================
-- Table: STATUS
-- ==================================================
DELETE FROM SUB.STATUS;

-- ==================================================
-- Table: PARTICIPANT
-- ==================================================
DELETE FROM SUB.PARTICIPANT p WHERE PARTICIPANT_ID = 2

-- ==================================================
-- Table: BOTANICSYSTEM
-- ==================================================
INSERT INTO SUB.BOTANICSYSTEM (BOTANICSYSTEM_VERSION, BOTANICSYSTEM_ORDINAL, BOTANICSYSTEM_ORDNUNG, BOTANICSYSTEM_FAMILIE, BOTANICSYSTEM_UNTERFAMILIE)
VALUES
	 (0, 70, 'CONIFERALES', 'Taxaceae', '')

DELETE FROM SUB.BOTANICSYSTEM

DELETE FROM SUB.BOTANICSYSTEM bs WHERE bs.BOTANICSYSTEM_ID = 70

-- ==================================================
-- Table: TIMBER
-- ==================================================
INSERT INTO SUB.TIMBER (TIMBER_VERSION, TIMBER_TYPE, TIMBER_CODE, TIMBER_ORIGIN_ID, TIMBER_NAME, TIMBER_IMAGENAME, TIMBER_AKADEMISCHERNAME, TIMBER_BOTANICSYSTEM_ID, TIMBER_ROHDICHTE, TIMBER_ZUGFESTIGKEIT, TIMBER_DRUCKFESTIGKEIT,
	TIMBER_BIEGEFESTIGKEIT, TIMBER_SCHERFESTIGKEIT, TIMBER_BRINELL_HAERTE1, TIMBER_BRINELL_HAERTE2, TIMBER_TANGENTIALSCHWUND, TIMBER_RADIALSCHWUND)
VALUES
	 (0, 'L', 'TXBC', 10, 'Eibe', 'eibe', 'Taxus baccata', 71, '0,59 - 0,63', '108', '56 - 58', '85', '', '70', '30', '5,7', '3,7')

INSERT INTO SUB.TIMBER (TIMBER_VERSION, TIMBER_TYPE, TIMBER_CODE, TIMBER_ORIGIN_ID, TIMBER_NAME, TIMBER_IMAGENAME, TIMBER_AKADEMISCHERNAME, TIMBER_BOTANICSYSTEM_ID, TIMBER_ROHDICHTE, TIMBER_ZUGFESTIGKEIT, TIMBER_DRUCKFESTIGKEIT,
	TIMBER_BIEGEFESTIGKEIT, TIMBER_SCHERFESTIGKEIT, TIMBER_BRINELL_HAERTE1, TIMBER_BRINELL_HAERTE2, TIMBER_TANGENTIALSCHWUND, TIMBER_RADIALSCHWUND)
VALUES
	 (0, 'L', 'ZZZZ', 12, 'Utopia', '', 'Utopia utopia', 69, '0,1 - 0,5', '', '', '', '', '', '', '', '')

DELETE FROM SUB.TIMBER

DELETE FROM SUB.TIMBER t WHERE t.TIMBER_ID = 233

UPDATE SUB.TIMBER t SET t.TIMBER_NAME = 'Ulme (Rot)' WHERE t.TIMBER_ID = 224

SELECT * FROM SUB.TIMBER t WHERE t.TIMBER_NAME LIKE '%Eiche%' OR t.TIMBER_NAME LIKE '%eiche%'

SELECT * FROM SUB.TIMBER t WHERE t.TIMBER_NAME LIKE '%Linde%' OR t.TIMBER_NAME LIKE '%inde%'

SELECT * FROM SUB.TIMBER t WHERE t.TIMBER_NAME LIKE '%Eibe%' OR t.TIMBER_NAME LIKE '%ibe%'

SELECT * FROM SUB.TIMBER t WHERE t.TIMBER_NAME LIKE '%Walnuss%' OR t.TIMBER_NAME LIKE '%alnuss%'

SELECT * FROM SUB.TIMBER t WHERE t.TIMBER_NAME LIKE '%uss%'

SELECT * FROM SUB.TIMBER t WHERE t.TIMBER_ORIGIN_ID = 10

SELECT * FROM SUB.TIMBER t WHERE t.TIMBER_BOTANICSYSTEM_ID = 20

SELECT * FROM SUB.BOTANICSYSTEM b WHERE BOTANICSYSTEM_ID = 20

SELECT COUNT(*) FROM SUB.TIMBER t WHERE t.TIMBER_NAME LIKE '%iche%'

SELECT DISTINCT(t.TIMBER_BOTANICSYSTEM_ID) FROM SUB.TIMBER t

-- ==================================================
-- Table: ARTEFACT
-- ==================================================
INSERT INTO SUB.ARTEFACT (ARTEFACT_VERSION, ARTEFACT_ORDINAL, ARTEFACT_TIMBER_ID, ARTEFACT_HERSTELLUNGSJAHR, ARTEFACT_PREIS,
	ARTEFACT_DURCHMESSER, ARTEFACT_HOEHE, ARTEFACT_WANDSTAERKE,	ARTEFACT_STATUS_ID, ARTEFACT_HERKUNFT, ARTEFACT_BESCHREIBUNG)
VALUES
	 (0, 3, 6, '2015', 100.0, 14.0, 12.0, 8.0, 5, '', 'Schale [Apfelbaum]')

INSERT INTO SUB.ARTIFACT (ARTEFACT_VERSION, ARTEFACT_ORDINAL, ARTEFACT_TIMBER_ID, ARTEFACT_HERSTELLUNGSJAHR, ARTEFACT_PREIS,
	ARTEFACT_DURCHMESSER, ARTEFACT_HOEHE, ARTEFACT_WANDSTAERKE,	ARTEFACT_STATUS_ID, ARTEFACT_HERKUNFT, ARTEFACT_BESCHREIBUNG)
VALUES
	 (0, 4, 20, '2015', 150.0, 14.0, 12.0, 8.0, 5, '', 'Schale [Zwetschge]')

UPDATE SUB.ARTEFACT
	SET ARTEFACT_BESCHREIBUNG='Diskus [Deutsche Walnuss]'
	WHERE ARTEFACT_ORDINAL = 1

DELETE FROM SUB.ARTEFACT a WHERE a.ARTEFACT_ID = 1

SELECT * FROM SUB.ARTEFACT

-- ==================================================
-- Table: MODIFICATION/MODSTEP INNER JOIN
-- ==================================================
SELECT *
FROM SUB.MODIFICATION
RIGHT OUTER JOIN SUB.MODPROCESS
ON MODIFICATION_ID = MODPROCESS_MODIFICATION_ID
WHERE MODPROCESS_MODIFICATION_ID = 1;
