/*==============================================================
DBMS     :  H2
Version  :  1.4.193
Database :  superbowlDB
Created  :  09.03.2017 00:00:00
Modified :  24.05.2017 00:00:00
==============================================================*/

/*==============================================================
Table: Audit
==============================================================*/
create table if not exists Audit (
	 audit_id							bigint			generated by default as identity (start with 1, increment by 1)
	,audit_timestamp					timestamp		not null
	,audit_user							varchar(256)	not null default ''
	,audit_table						varchar(256)	not null default ''
	,audit_action						varchar(256)	not null default ''
	,audit_field01						varchar(256)	not null default ''
	,audit_field02						varchar(256)	not null default ''
	,audit_field03						varchar(256)	not null default ''
	,audit_field04						varchar(256)	not null default ''
	,audit_field05						varchar(256)	not null default ''
	,audit_field06						varchar(256)	not null default ''
	,audit_field07						varchar(256)	not null default ''
	,audit_field08						varchar(256)	not null default ''
	,audit_field09						varchar(256)	not null default ''
	,audit_field10						varchar(256)	not null default ''
	,audit_field11						varchar(256)	not null default ''
	,audit_field12						varchar(256)	not null default ''
	,audit_field13						varchar(256)	not null default ''
	,audit_field14						varchar(256)	not null default ''
	,audit_field15						varchar(256)	not null default ''
	,audit_field16						varchar(256)	not null default ''
	,audit_field17						varchar(256)	not null default ''
	,audit_field18						varchar(256)	not null default ''
	,audit_field19						varchar(256)	not null default ''
	,audit_field20						varchar(256)	not null default ''
	,constraint audit_pk primary key (audit_id)
);

comment on table Audit is 'Protocol table for all CRUD operations';

commit;