/*==============================================================
DBMS    :  H2
Version :  1.4.x
Database:  superbowlDB
Created :  07.03.2017 00:00:00
==============================================================*/

/*==============================================================
Drop Trigger
==============================================================*/
DROP TRIGGER ARTEFACT_AFTER_INSERT_TRIGGER if exists;
DROP TRIGGER ARTEFACT_BEFORE_UPDATE_TRIGGER if exists;
DROP TRIGGER ARTEFACT_AFTER_UPDATE_TRIGGER if exists;
DROP TRIGGER ARTEFACT_AFTER_DELETE_TRIGGER if exists;

DROP TRIGGER BOTANICSYSTEM_AFTER_INSERT_TRIGGER if exists;
DROP TRIGGER BOTANICSYSTEM_BEFORE_UPDATE_TRIGGER if exists;
DROP TRIGGER BOTANICSYSTEM_AFTER_UPDATE_TRIGGER if exists;
DROP TRIGGER BOTANICSYSTEM_AFTER_DELETE_TRIGGER if exists;

DROP TRIGGER GEOREGION_AFTER_INSERT_TRIGGER if exists;
DROP TRIGGER GEOREGION_BEFORE_UPDATE_TRIGGER if exists;
DROP TRIGGER GEOREGION_AFTER_UPDATE_TRIGGER if exists;
DROP TRIGGER GEOREGION_AFTER_DELETE_TRIGGER if exists;

DROP TRIGGER ACTOR_AFTER_INSERT_TRIGGER if exists;
DROP TRIGGER ACTOR_BEFORE_UPDATE_TRIGGER if exists;
DROP TRIGGER ACTOR_AFTER_UPDATE_TRIGGER if exists;
DROP TRIGGER ACTOR_AFTER_DELETE_TRIGGER if exists;

DROP TRIGGER ACTORROLE_AFTER_INSERT_TRIGGER if exists;
DROP TRIGGER ACTORROLE_BEFORE_UPDATE_TRIGGER if exists;
DROP TRIGGER ACTORROLE_AFTER_UPDATE_TRIGGER if exists;
DROP TRIGGER ACTORROLE_AFTER_DELETE_TRIGGER if exists;

DROP TRIGGER ACTORSESSION_AFTER_INSERT_TRIGGER if exists;
DROP TRIGGER ACTORSESSION_BEFORE_UPDATE_TRIGGER if exists;
DROP TRIGGER ACTORSESSION_AFTER_UPDATE_TRIGGER if exists;
DROP TRIGGER ACTORSESSION_AFTER_DELETE_TRIGGER if exists;

DROP TRIGGER ACTORIDENTITY_AFTER_INSERT_TRIGGER if exists;
DROP TRIGGER ACTORIDENTITY_BEFORE_UPDATE_TRIGGER if exists;
DROP TRIGGER ACTORIDENTITY_AFTER_UPDATE_TRIGGER if exists;
DROP TRIGGER ACTORIDENTITY_AFTER_DELETE_TRIGGER if exists;

DROP TRIGGER STATUS_AFTER_INSERT_TRIGGER if exists;
DROP TRIGGER STATUS_BEFORE_UPDATE_TRIGGER if exists;
DROP TRIGGER STATUS_AFTER_UPDATE_TRIGGER if exists;
DROP TRIGGER STATUS_AFTER_DELETE_TRIGGER if exists;

DROP TRIGGER TIMBER_AFTER_INSERT_TRIGGER if exists;
DROP TRIGGER TIMBER_BEFORE_UPDATE_TRIGGER if exists;
DROP TRIGGER TIMBER_AFTER_UPDATE_TRIGGER if exists;
DROP TRIGGER TIMBER_AFTER_DELETE_TRIGGER if exists;

DROP TRIGGER MODIFICATION_AFTER_INSERT_TRIGGER if exists;
DROP TRIGGER MODIFICATION_BEFORE_UPDATE_TRIGGER if exists;
DROP TRIGGER MODIFICATION_AFTER_UPDATE_TRIGGER if exists;
DROP TRIGGER MODIFICATION_AFTER_DELETE_TRIGGER if exists;

DROP TRIGGER MODSTEP_AFTER_INSERT_TRIGGER if exists;
DROP TRIGGER MODSTEP_BEFORE_UPDATE_TRIGGER if exists;
DROP TRIGGER MODSTEP_AFTER_UPDATE_TRIGGER if exists;
DROP TRIGGER MODSTEP_AFTER_DELETE_TRIGGER if exists;

DROP TRIGGER MODPROCESS_AFTER_INSERT_TRIGGER if exists;
DROP TRIGGER MODPROCESS_BEFORE_UPDATE_TRIGGER if exists;
DROP TRIGGER MODPROCESS_AFTER_UPDATE_TRIGGER if exists;
DROP TRIGGER MODPROCESS_AFTER_DELETE_TRIGGER if exists;

commit;